blog/urls.py
from django.urls import path

from comment.urls import urlpatterns as comment_urls
from .views import ArticleListView, ArticleCategoryView, ArticleTopicView, SearchArticleView, \
    ArticleDetailView, HomeView, UploadImageView, CategoryListView, TopicListView, LinkListView


app_name = 'blog'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('topic/', TopicListView.as_view(), name='topic_list'),
    path('link/', LinkListView.as_view(), name='link_list'),
    path('article/', ArticleListView.as_view(), name='article_list'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='detail'),
    path('article/category/<int:category_id>/', ArticleCategoryView.as_view(), name='category'),
    path('article/topic/<int:topic_id>/', ArticleTopicView.as_view(), name='topic'),
    path('article/search/', SearchArticleView.as_view(), name='search'),
    path('article/upload/image/', UploadImageView.as_view(), name='upload_image'),
] + comment_urls

fossensite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

from async_task.views import deploy_view
from tools.views import CSRFView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('blog.urls')),
    path('api/account/', include('account.urls')),
    path('api/csrf/', CSRFView.as_view(), name='csrf'),
    path('api/deploy/', deploy_view, name='deploy'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error handler
handler400 = 'tools.views.bad_request'
handler403 = 'tools.views.permission_denied'
handler404 = 'tools.views.page_not_found'
handler500 = 'tools.views.server_error'

blog/models.py
'博客应用模型'
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# from django.core.cache import cache
# from django.core.cache.utils import make_template_fragment_key


class Category(models.Model):
    name = models.CharField('分类', max_length=16)
    number = models.PositiveIntegerField('次序', default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'https://www.fossen.cn/article/category/{self.pk}'

    class Meta:
        ordering = ['number']
        verbose_name = '分类'
        verbose_name_plural = '分类'


class Topic(models.Model):
    name = models.CharField('话题', max_length=16)
    number = models.PositiveIntegerField('次序', default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'https://www.fossen.cn/article/topic/{self.pk}'

    class Meta:
        ordering = ['number']
        verbose_name = '话题'
        verbose_name_plural = '话题'


class Article(models.Model):
    '文章'
    title = models.CharField('标题', max_length=100)
    cover = models.ImageField(
        upload_to='blog/cover', blank=True, null=True, verbose_name='封面图')
    content = models.TextField('内容')
    pub_date = models.DateTimeField('发布日期')
    # 作者与分类的默认值为2和1,代表着相应数据库中id的字段,分别手动将其设置为了fossen和未分类
    author = models.ForeignKey(
        User, default=2, on_delete=models.SET_DEFAULT, verbose_name='作者')
    category = models.ForeignKey(
        Category, default=1, on_delete=models.SET_DEFAULT, verbose_name='分类')
    topics = models.ManyToManyField(Topic, verbose_name='话题')
    views = models.PositiveIntegerField('阅读量', default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'https://www.fossen.cn/article/{self.pk}'

    def increase_views(self):
        self.views += 1
        super().save(update_fields=['views'])

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     # 保存后清空相关缓存
    #     cache.delete(make_template_fragment_key('home'))
    #     cache.delete(make_template_fragment_key('article_detail', [self.id]))
    #     cache.delete(make_template_fragment_key(
    #         'article_detail_title', [self.id]))
    #     c_pages = self.category.article_set.count()//10 + 1
    #     for i in range(1, c_pages+1):
    #         cache.delete(make_template_fragment_key(
    #             'article_category', [self.category.id, i]))
    #     for topic in self.topics.all():
    #         t_pages = topic.article_set.count()//10 + 1
    #         for i in range(1, t_pages+1):
    #             cache.delete(make_template_fragment_key(
    #                 'article_topic', [topic.id, i]))

    class Meta:
        ordering = ['-pub_date']
        verbose_name = '文章'
        verbose_name_plural = '文章'
        indexes = [
            models.Index(fields=['-pub_date'])
        ]


class Link(models.Model):
    '友情链接'
    name = models.CharField('网站名', max_length=100)
    url = models.CharField('网址', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = '友情链接'

blog/views.py
from django.core.exceptions import SuspiciousOperation
from django.core.files.storage import default_storage
from django.conf import settings
from django.utils import timezone
from django.db.models import Q

from tools.views import ListView, DetailView, JSONView
from .models import Article, Category, Topic, Link


class CategoryListView(ListView):
    model = Topic
    context_object_name = 'cates'

    def get_queryset(self):
        return Category.objects.filter(number__gt=0)

    def serialize(self):
        data = super().serialize()
        context = self.context
        cates = []
        for i in context['cates']:
            cates.append({
                'id': i.id,
                'name': i.name,
            })
        data['data'] = cates
        return data


class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.filter(number__gt=0)

    def serialize(self):
        data = super().serialize()
        context = self.context
        topics = []
        for i in context['topics']:
            topics.append({
                'id': i.id,
                'name': i.name,
            })
        data['data'] = topics
        return data


class LinkListView(ListView):
    model = Link
    context_object_name = 'links'

    def serialize(self):
        data = super().serialize()
        context = self.context
        links = []
        for i in context['links']:
            links.append({
                'id': i.id,
                'name': i.name,
                'url': i.url
            })
        data['data'] = links
        return data


def serialize_article(article):
    result = {
        'id': article.id,
        'cover': article.cover.url if article.cover else None,
        'title': article.title,
        'content': article.content,
        'views': article.views,
        'pub_date': article.pub_date.isoformat(),
        'category': {
            'id': article.category.id,
            'name': article.category.name,
        },
        'topics': [{
            'id': t.id,
            'name': t.name,
        } for t in article.topics.all()],
    }
    return result


class ArticleListView(ListView):
    '文章列表视图'
    model = Article
    context_object_name = 'articles'
    paginate_by = 10
    allow_empty = True

    def get_queryset(self):
        return super().get_queryset() \
            .filter(pub_date__lt=timezone.now()) \
            .filter(category__number__gt=0) \
            .defer('author') \
            .select_related('category') \
            .prefetch_related('topics')

    def serialize(self):
        data = super().serialize()
        context = self.context
        articles = []
        for article in context['articles']:
            item = serialize_article(article)
            articles.append(item)
        data['data'] = articles
        return data


class HomeView(ArticleListView):
    '首页视图'


class ArticleCategoryView(ArticleListView):
    '文章分类视图'

    def get_queryset(self):
        return super().get_queryset().filter(category=self.kwargs['category_id'])


class ArticleTopicView(ArticleListView):
    '文章话题视图'

    def get_queryset(self):
        return super().get_queryset().filter(topics=self.kwargs['topic_id'])


class SearchArticleView(ArticleListView):
    '文章搜索视图'

    def get_queryset(self):
        q = self.request.GET['q']
        ql = len(q)
        if ql < 0 or ql > 88:
            raise SuspiciousOperation('搜索关键字长度必须在 0 ~ 88 之间')
        q = q.split(' ')
        while '' in q:
            q.remove('')
        queryset = super().get_queryset()
        for k in q:
            queryset = queryset.filter(
                Q(title__icontains=k) | Q(content__icontains=k))
        return queryset


class ArticleDetailView(DetailView):
    '文章详情视图'
    model = Article

    def get_context_data(self):
        article = self.object  # type: Article
        data = serialize_article(article)
        # 每处理一次get请求就增加一次阅读量
        article.increase_views()
        return data


class UploadImageView(JSONView):
    def post(self, request):
        image = request.FILES.get('upload_image')
        if not image or image.name.split('.')[-1] not in ['jpg', 'jpeg', 'png', 'bmp', 'gif']:
            return {
                'success': False,
                'file_path': '',
                'msg': 'Unexpected File Format!'
            }

        file_path = settings.MEDIA_ROOT + '/blog/image/' + image.name[-10:]
        file_path = default_storage.save(file_path, image)
        return {
            'success': True,
            # 返回的是文件的url
            'file_path': settings.MEDIA_URL + 'blog/image/' + file_path.split('/')[-1],
            'msg': 'Success!'
        }

templates/blog/detail.html
{% extends 'base.html' %} {% load blog_tags %}  {% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="white-board ariticle-detail">
                <div class="breadcrumb-nav">
                    <a href="/">首页</a> &gt;
                    <a href="{% url 'blog:category' 0 %}">文章</a> &gt;
                    <a href="{% url 'blog:category' article.category.pk %}">
                        {{ article.category }}
                    </a>
                </div>
                <article>
                    {% if article.cover %}
                    <div class="cover">
                        <img src="{{ article.cover.url }}">
                    </div>
                    {% endif %}
                    <h1 class="title">{{ article.title }}</h1>
                    <div class="meta">
                        {{ article.pub_date }} &emsp;{{ article.views }} 阅读&emsp;
                        <a href="#comment">
                            0 评论
                        </a>&emsp;分类:&nbsp;
                        <a href="{% url 'blog:category' article.category.pk %}">
                            {{ article.category }}
                        </a>&emsp;话题:&nbsp;{% for topic in article.topics.all %}
                        <a href="{% url 'blog:topic' topic.pk %}">{{ topic.name }}</a>&nbsp;{% endfor %}
                    </div>
                    <div class="content">
                        {{ article.content|safe }}
                    </div>
                </article>
                <div id='comment'>
                    <ul class="comment-list list-unstyled">
                        {% for comment in comment_list %}
                        <li class="comment-item">
                            <span class="nickname">{{ comment.user }}</span>
                            <time class="submit-date">{{ comment.pub_date }}</time>
                            <div class="content">
                                {{ comment.content }}
                            </div>
                        </li>
                        {% empty %} 暂无评论 {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="white-board widget">
                <h6 class="widget-title">分类</h6>
                <ul class="category-widget">
                    <li>
                        <a href="{% url 'blog:category' 0 %}">
                            全部文章
                        </a>
                    </li>
                    {% get_article_category_names as categories %}
                    {% for cate in categories %}
                    <li>
                        <a href="{% url 'blog:category' cate.pk %}">
                            {{ cate.name }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock main %}